"use client";

import { Provider } from "react-redux";
import { store } from "@/store";
import "./globals.css";
import Navbar from "@/components/NavBar";
import { useCheckAuthQuery } from "@/store/apiSlice";
import { useRouter, usePathname } from "next/navigation";
import { useEffect } from "react";

function AuthWrapper({ children }: { children: React.ReactNode }) {
  const { data: authData, isLoading } = useCheckAuthQuery();
  const router = useRouter();
  const pathname = usePathname();

  useEffect(() => {
    if (!isLoading && authData) {
      const isAuthenticated = authData.isAuthenticated;
      const isAuthRoute = pathname.startsWith("/auth");

      if (!isAuthenticated) {
        router.push("/auth/login");
      } else if (isAuthenticated && isAuthRoute) {
        router.push("/");
      }
    }
  }, [isLoading, authData, router, pathname]);

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-screen">
        Loading...
      </div>
    );
  }

  const isLoggedIn = authData?.isAuthenticated || false;

  return (
    <>
      {isLoggedIn && (
        <div className="fixed top-0 left-0 right-0 z-50 py-4 px-6 flex items-center justify-between">
          <div
            className="font-bold text-gray-900 text-4xl pt-6 cursor-pointer"
            onClick={() => router.push("/")}
          >
            DebtX
          </div>
          <Navbar />
        </div>
      )}
      <div className="pt-[6.5rem]">{children}</div>{" "}
      {/* Space for fixed header */}
    </>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>DebtX - Dashboard</title>
        <meta
          name="description"
          content="Manage your debts with ease - Generated by Jatin"
        />
      </head>
      <body className="min-h-screen bg-gray-100">
        <Provider store={store}>
          <AuthWrapper>{children}</AuthWrapper>
        </Provider>
      </body>
    </html>
  );
}
