import { Metadata } from "next";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = {
  title: "DebtX - Collection Management",
  description: "Manage your debts with ease - Generated by Jatin",
};

export default function LandingPage() {
  // No direct cookie check here—layout.tsx handles auth redirect
  return (
    <div className="flex items-center justify-center min-h-screen w-full bg-gray-100">
      <div className="flex flex-col items-center gap-8 p-8 bg-white rounded-xl shadow-md w-full max-w-lg mx-4">
        <h1 className="text-4xl font-extrabold text-gray-900">DebtX</h1>
        <p className="text-lg text-gray-600 text-center max-w-xs">
          Your ultimate solution for debt collection and management
        </p>
        <div className="flex flex-col items-center gap-4 w-full">
          <Link href="/auth/login" className="w-full">
            <Button className="w-full bg-blue-600 hover:bg-blue-700 text-white py-2">
              Login
            </Button>
          </Link>
          <p className="text-sm text-gray-500 text-center">
            Don’t have an account?{" "}
            <Link href="/auth/signup" className="text-blue-600 hover:underline">
              Sign Up
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}
