import { Metadata } from "next";
import Link from "next/link";
import { cookies } from "next/headers"; // Server-side cookie access
import { Button } from "@/components/ui/button";

export const metadata: Metadata = {
  title: "DebtX - Collection Management",
  description: "Manage your debts with ease - Generated by Jatin",
};

export default async function LandingPage() {
  const cookieStore = await cookies(); // Async in Next.js 14
  const sessionCookie = cookieStore.get("session"); // Synchronous after awaiting cookies()

  return (
    <div className="flex items-center justify-center h-screen w-full bg-gradient-to-br from-blue-500 to-purple-600">
      <div className="flex flex-col items-center gap-6 p-8 bg-white rounded-xl shadow-lg w-full max-w-md">
        <h1 className="text-4xl font-extrabold text-gray-800">DebtX</h1>
        <p className="text-lg text-gray-600 text-center">
          Your ultimate solution for debt collection and management
        </p>
        {sessionCookie ? (
          <div className="flex flex-col items-center gap-4">
            <p className="text-green-600">Welcome back!</p>
            <Link href="/customers">
              <Button className="w-full bg-blue-600 hover:bg-blue-700">
                Go to Dashboard
              </Button>
            </Link>
          </div>
        ) : (
          <div className="flex flex-col items-center gap-4 w-full">
            <Link href="/auth/login" className="w-full">
              <Button className="w-full bg-blue-600 hover:bg-blue-700">
                Login
              </Button>
            </Link>
            <p className="text-sm text-gray-500">
              Don&apos;t have an account?{" "}
              <Link
                href="/auth/signup"
                className="text-blue-600 hover:underline"
              >
                Sign Up
              </Link>
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
